name: flutter_playground
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: one-isolate
      path: audio_service
  audio_video_progress_bar: ^0.4.0
  get_it: ^7.1.2
  just_audio: ^0.7.4
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
